import React from "react";
import Home from "./home";
import Head from "next/head";

const Index = () => {
 return (
  <div>
   <Head>
    <title>BTPN Test CRUD</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
   </Head>
   <Home />
  </div>
 );
};

export default Index;
